version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapi
      - /myapi/temp/
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true
  # front:
  #   container_name: nuxt
  #   build: ./front/EE-SPORTS
  #   command: npm run dev
  #   volumes:
  #     - ./front/EE-SPORTS:/app
  #     - /app/node_modules/
  #   ports:
  #     - "3000:3000"
  #   tty: true